#cloud-config

users:
  - name: c0dexec
    gecos: c0dexec
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, sudo
    lock_passwd: false
    # Using openssl we get the hash `openssl passwd -1 -salt cheeku salmon`
    passwd: $1$cheeku$9jRkbPoaRv2r..GQM/tzt0
    # ssh_authorized_keys:
    #   - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHyPwq2ILHi+KzZjNWt9YPYXhIZAsg0QJWbBl9yO7N2SmAEVB2GZPTuhK7X/D3qQHQKBy+NseeB4YapEO8B9qaXSgFvybwcaDlbMDtH3s4XaVtoVqtoEF+WRt6/iH707JEHi3+wxyaVl4saG+PqqIwiiMnRVaqKiTzgt8a0h27pO/wWPg== root@pve-R730
    #   - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFD5KEaRSysh/sT/hlpUvz9CxkZqGaPTHcPm+48D3Cb5eaGYH0Kd3GG6Hg5g//M7SyG6+jSUJnduI2zcOjkh60EFwA+ldQ3xKHEXrB13Pph4k2E5Yx2VnaIOG7amm0Q33Aey/URgu5JnC4dO92o/W63ZsmOWt+ztoigxigOaz2l9pNV+g== root@pve-R730

packages:
  - ssh
  - qemu-guest-agent

runcmd:
  - "sudo systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent"